version: '3'

services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app/backend
    depends_on:
      - database
    env_file:
      - .env

  frontend:
    build: ./Frontend
    ports:
      - "80:80"

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"